version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/status-page
hooks:
  BeforeInstall:
#     - location: scripts/install_codedeploy_agent.sh
#       timeout: 300
#       runas: root
    - location: scripts/setup_db_redis.sh
      timeout: 300
      runas: root
  
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root
