version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/status-page
hooks:
  BeforeInstall:
    - location: scripts/install_codedeploy_agent.sh
      timeout: 300
      runas: ubuntu
  
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 180
      runas: ubuntu
