version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/status-page
hooks:
  BeforeInstall:
    - location: ./scripts/before_installation.sh
      timeout: 300
      runas: root
  
  ApplicationStart:
    - location: ./scripts/application_start.sh
      timeout: 300
      runas: root
