version: '3'

services:
  db-redis:
    build: ./postgres-redis/
    container_name: postgresql-redis
    environment:
      POSTGRES_USER: statuspage
      POSTGRES_PASSWORD: Aa123456123456
      POSTGRES_DB: status-page
    volumes:
      - ./init.sql/db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
      - "6379:6379"

  application:
    build: .
    depends_on:
      - db-redis
    container_name: app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://statuspage:Aa123456123456@postgres:5432/status-page
      REDIS_URL: redis://redis:6379/0
volumes:
  db.sql:
