version: '2.9'
services:
  redis:
    image: redis:7.0.8-alpine
    container_name: redis
    restart: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - statuspage
  
  db:
    image: postgres:15.2-alpine
    container_name: postgresql
    restart: on-failure
    environment:
      POSTGRES_USER: "statuspage"
      POSTGRES_PASSWORD: "Aa123456123456"
      POSTGRES_DB: "status-page"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d statuspage -U statuspage"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./init.sql/db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    networks:
      - statuspage

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    container_name: app
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://statuspage:Aa123456123456@db:5432/statuspage
      REDIS_URL: redis://redis:6379/0
    networks:
      - statuspage

volumes:
  db.sql:
  postgresql.conf:
  redis.conf:

networks:
  statuspage:
