version: '3'
services:
  redis:
    image: redis:7.0.8-alpine
    container_name: redis
    restart: on-failure
    healthcheck:
      test: "redis-cli ping"
      interval: 1s
      retries: 20
    ports:
      - "6379:6379"
  
  db:
    image: postgres
    container_name: postgresql
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD='Aa123456123456' psql -U statuspage -p 5432 -c 'SELECT 1' statuspage"
      interval: 1s
      retries: 20
    environment:
      POSTGRES_USER: "statuspage"
      POSTGRES_PASSWORD: "Aa123456123456"
      POSTGRES_DB: "statuspage"
    volumes:
      - ./init.sql/db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"

  application:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    container_name: app
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://statuspage:Aa123456123456@postgres:5432/status-page
      REDIS_URL: redis://redis:6379/0

volumes:
  db.sql:
  postgresql.conf:
