version: '3'
services:
  redis:
    image: redis:7.0.8-alpine
    container_name: redis
    healthcheck:
      test: "redis-cli ping"
      interval: 1s
      retries: 20
    ports:
      - "6379:6379"
  
  db:
    image: postgres
    container_name: postgresql
    restart: on-failure
    environment:
      POSTGRES_USER: statuspage
      POSTGRES_PASSWORD: Aa123456123456
      POSTGRES_DB: status-page
    healthcheck:
      test: "PGPASSWORD='Aa123456123456' psql -U statuspage -p 5432 -c 'SELECT 1' statuspage"
      interval: 1s
      retries: 20
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /var/run/postgresql:/var/run/postgresql
    ports:
      - "5432:5432"
    command: >
      bash -c "echo 'CREATE DATABASE status-page;' | psql -U postgres &&
               echo \"CREATE USER statuspage WITH ENCRYPTED PASSWORD 'Aa123456123456';\" | psql -U postgres &&
               echo 'GRANT ALL PRIVILEGES ON DATABASE mydb TO myuser;' | psql -U postgres"

  application:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    container_name: app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://statuspage:Aa123456123456@postgres:5432/status-page
      REDIS_URL: redis://redis:6379/0

volumes:
  init.sql:
  postgresql:
