name: Build, test, push and deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
        
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          chmod +x tests/check-http-request.sh
          ./tests/check-http-request.sh
          
  build_push:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    steps:
      # need checkout before using compose-action
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: status-page
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG  
      
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          
      - name: Start CodeDeploy Deployment
        id: start_deploy
        run: |
          aws deploy create-deployment \
            --application-name CICD \
            --deployment-group-name CICDGROUP \
            --revision revisionType=ECR,imageName=status-page:latest \
            --description "Deployment initiated by GitHub Actions" \
            --file-exists-behavior OVERWRITE
